# Generated by Django 3.0.6 on 2020-07-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='about',
            name='last_name',
            field=models.CharField(default='Garg', max_length=30),
            preserve_default=False,
        ),
    ]
