# Generated by Django 3.0.6 on 2020-08-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200810_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcast',
            new_name='Media',
        ),
    ]
