# Generated by Django 3.0.6 on 2020-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200704_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='icon',
            field=models.CharField(max_length=40),
        ),
    ]
