# Generated by Django 3.0.6 on 2020-07-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200727_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='icon',
        ),
    ]
