# Generated by Django 3.0.6 on 2020-08-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_article_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, default='1008/2020'),
            preserve_default=False,
        ),
    ]
