# Generated by Django 3.0.6 on 2020-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200801_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
