# Generated by Django 3.0.6 on 2020-08-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200801_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=300)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
