# Generated by Django 3.0.6 on 2020-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
