# Generated by Django 3.0.6 on 2020-09-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_game_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Arcade', max_length=20),
            preserve_default=False,
        ),
    ]
