# Generated by Django 3.0.6 on 2020-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='itch_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='play_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
