# Generated by Django 3.0.6 on 2020-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnityGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('play_link', models.URLField(default='#')),
                ('itch_link', models.URLField(default='#')),
                ('image', models.ImageField(upload_to='gameimages')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
