# Generated by Django 3.0.6 on 2020-09-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_auto_20200926_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnityGame',
        ),
    ]
